from __future__ import annotations

import os
import subprocess
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
CONTEXTKIT = REPO_ROOT / "bin" / "contextkit"
CAPABILITIES_PROVIDER = REPO_ROOT / "tests" / "fixtures" / "capabilities"
GUIDE_TOPICS = [
    "bootstrap",
    "authoring",
    "agent-team",
    "workbench",
    "global-context",
    "memory",
    "validation",
    "assets",
    "routines",
    "audit",
    "groom",
    "destructive",
    "migration",
    "hooks",
    "capabilities",
]


class GeneratedContextTests(unittest.TestCase):
    def run_cli(self, *args: str, cwd: Path,
                capabilities_manager: str | Path = CAPABILITIES_PROVIDER) -> subprocess.CompletedProcess[str]:
        env = dict(os.environ)
        env["CAPABILITIES_MANAGER"] = str(capabilities_manager)
        return subprocess.run(
            [str(CONTEXTKIT), *args],
            cwd=cwd,
            env=env,
            text=True,
            capture_output=True,
            check=False,
        )

    def initialize(self, project: Path, with_layers: bool = True) -> None:
        args = ["init", "--json"]
        if with_layers:
            args.insert(1, "--with-layers")
        initialized = self.run_cli(*args, cwd=project)
        self.assertEqual(initialized.returncode, 0, initialized.stderr)

    def build(self, project: Path, target: str) -> None:
        built = self.run_cli("build", "--target", target, cwd=project)
        self.assertEqual(built.returncode, 0, built.stderr)

    def test_generated_headers_are_minimal_and_target_specific(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp) / "project"
            project.mkdir()
            self.initialize(project)
            self.build(project, "all")

            targets = {
                "codex": project / ".codex" / "generated" / "context.md",
                "claude": project / ".claude" / "rules" / "CONTEXT.md",
            }
            for target, path in targets.items():
                with self.subTest(target=target):
                    generated = path.read_text()
                    title = "Codex" if target == "codex" else "Claude"
                    header = generated.split("\n---\n", 1)[0].rstrip()
                    self.assertEqual(
                        header,
                        "\n".join([
                            f"# {title} Context",
                            "",
                            "<!-- Generated by ContextKit. Do not edit by hand. -->",
                            "Source config: `.contextkit/config.toml`",
                            f"Rebuild: `contextkit build --target {target}`",
                        ]),
                    )
                    for redundant in [
                        "Context manager:",
                        "Bootstrap:",
                        "Doctor:",
                        "Help:",
                        "Rule sources:",
                        "Compiled source directories:",
                        "Context load modes:",
                        "Inline files:",
                        "Stub files:",
                        "Memory files:",
                        "Global inline files:",
                        "Global stub files:",
                    ]:
                        self.assertNotIn(redundant, header)
                    self.assertNotIn("Generated host context is delivery output. Rebuild it from source", generated)

    def test_guide_menu_is_the_single_generated_guide_index(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp) / "project"
            project.mkdir()
            self.initialize(project)
            self.build(project, "codex")

            generated = (project / ".codex" / "generated" / "context.md").read_text()
            self.assertEqual(generated.count("# Guide Menu"), 1)
            menu = generated.split("# Guide Menu", 1)[1].split("\n---\n", 1)[0]
            guide_lines = [line for line in menu.splitlines() if line.startswith("- `contextkit guide ")]
            self.assertEqual(len(guide_lines), len(GUIDE_TOPICS))
            for topic in GUIDE_TOPICS:
                self.assertEqual(sum(line.startswith(f"- `contextkit guide {topic}` - ") for line in guide_lines), 1)

    def test_generation_warnings_appear_only_when_present(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            complete = root / "complete"
            complete.mkdir()
            self.initialize(complete)
            self.build(complete, "codex")
            complete_generated = (complete / ".codex" / "generated" / "context.md").read_text()
            self.assertNotIn("Generation warnings:", complete_generated)

            incomplete = root / "incomplete"
            incomplete.mkdir()
            self.initialize(incomplete, with_layers=False)
            (incomplete / "context").mkdir()
            self.build(incomplete, "codex")
            incomplete_generated = (incomplete / ".codex" / "generated" / "context.md").read_text()
            self.assertIn("Generation warnings:", incomplete_generated)
            self.assertIn("routine layer not present", incomplete_generated)
            self.assertIn("capability layer not present", incomplete_generated)

    def test_capability_context_is_inserted_opaquely_from_manager(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp) / "project"
            project.mkdir()
            self.initialize(project)
            (project / "capabilities" / "settings.json").write_text(
                '{"capabilities":{"contextkit-must-not-render":{"enabled":true}}}\n'
            )

            self.build(project, "codex")

            generated = (project / ".codex" / "generated" / "context.md").read_text()
            provider_block = "\n".join([
                "# Capabilities",
                "",
                "<!-- capabilities:begin — fixture manager-owned block -->",
                "",
                "Manager-owned capability intro.",
                "",
                "## provider-only",
                "",
                "This capability was rendered by the provider fixture.",
                "",
                "<!-- capabilities:end -->",
            ])
            self.assertIn(provider_block, generated)
            self.assertNotIn("contextkit-must-not-render", generated)
            self.assertNotIn("Capability index - generated by", generated)

    def test_capability_provider_failure_warns_without_local_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp) / "project"
            project.mkdir()
            self.initialize(project)
            (project / "capabilities" / "settings.json").write_text(
                '{"capabilities":{"contextkit-must-not-render":{"enabled":true}}}\n'
            )

            built = self.run_cli(
                "build", "--target", "codex", cwd=project,
                capabilities_manager=project / "missing-capabilities-manager",
            )

            self.assertEqual(built.returncode, 0, built.stderr)
            generated = (project / ".codex" / "generated" / "context.md").read_text()
            self.assertIn("capability context omitted: manager provider could not run", generated)
            self.assertNotIn("contextkit-must-not-render", generated)
            self.assertNotIn("# Capabilities", generated)


if __name__ == "__main__":
    unittest.main()
